<!DOCTYPE html>
<!--
Copyright (c) 2003-2019, CKSource - Frederico Knabben. All rights reserved.
For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
-->
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
	<title>CKEditor 5 – classic editor build sample</title>
</head>
<body>

<main>
    <div id="example"></div>
</main>

<script>var editor = new FroalaEditor('#example');</script>
</body>
</html>
