


<h3 class="text-2xl text-orange-700 font-bold mb-6 ml-5 mt-4">Catégories d'articles</h3>

<ol class="flex flex-wrap">
  <div>
    <form action="?goto=<?= $this->datacrypt('CategoryController') ?>&action=<?= $this->datacrypt('addCategory')
                    ?>" method="post" class=" border-purple-600">

      <div class="md:flex flex-start">
    
        <div class="block p-6 rounded-lg shadow-lg bg-white-300 border-black-600 max-w-md ml-6 mb-10 shadow-2xl">
          <div class=" mb-4">
            <input id="category_name" class="font-medium text-orange-600 hover:text-purple-700 focus:text-purple-800 focus:border-orange-600 duration-300 transition ease-in-out text-sm py-3" placeholder="Nom de la catégorie"/>
            <!-- <input type="date" name="date" id="date" class="font-medium text-orange-600 hover:text-purple-700 focus:text-purple-800 duration-300 transition ease-in-out text-sm"> -->
            
          </div>
          <textarea class="text-balack-700 mb-6 pr-3" name="category_description" id="category_description" cols="45" rows="4" placeholder="Taper un petit commentaire pa rapport a cette nouvelle catégorie"></textarea>
          
          <button type="submit" id="validation_category" class="inline-block px-4 py-1.5 bg-yellow-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-purple-700 hover:shadow-lg focus:bg-purple-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-purple-800 active:shadow-lg transition duration-150 ease-in-out" data-mdb-ripple="true">Ajouter</button>
          <!-- <button type="button" class="inline-block px-4 py-1.5 bg-yellow-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-purple-700 hover:shadow-lg focus:bg-purple-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-purple-800 active:shadow-lg transition duration-150 ease-in-out" data-mdb-ripple="true">Spprimer</button> -->
          <!-- <button type="button" class="inline-block px-3.5 py-1 border-2 border-purple-600 text-orange-600 font-medium text-xs leading-tight uppercase rounded hover:bg-black hover:bg-opacity-5 focus:outline-none focus:ring-0 transition duration-150 ease-in-out" data-mdb-ripple="true">See demo</button> --> 
        </div>
      </div>
  </form>
  </div>
<?php foreach($allCategories as $key => $values) : ?>
  <div>
  <li class="border-purple-600 h-20">
    <div class="md:flex flex-start">
   
      <div class="block p-6 rounded-lg shadow-lg bg-white-300 border-black-600 max-w-md ml-6 mb-10 shadow-2xl">
        <div class="flex justify-between mb-4">
          <a href="#!" class="font-medium text-orange-600 hover:text-purple-700 focus:text-purple-800 duration-300 transition ease-in-out text-sm"><?= $values["category_name"] ?></a>
        </div>
        <p class="text-balack-700 mb-6"> Bref présentation : <?= $values["category_description"] ?></p>
        <button type="button" class="delete_category inline-block px-4 py-1.5 bg-yellow-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-purple-700 hover:shadow-lg focus:bg-purple-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-purple-800 active:shadow-lg transition duration-150 ease-in-out" data-mdb-ripple="true" value="<?= $values["category_id"] ?>">Supprimer</button>
        <!-- <button type="button" class="inline-block px-3.5 py-1 border-2 border-purple-600 text-orange-600 font-medium text-xs leading-tight uppercase rounded hover:bg-black hover:bg-opacity-5 focus:outline-none focus:ring-0 transition duration-150 ease-in-out" data-mdb-ripple="true">See demo</button> --> 
      </div>
    </div>
  </li>
  </div>
<?php endforeach; ?>

</ol>

<script src="/ressources/js/category.js"></script>

