

<button type="submit" id="submit" class="mb-4 text-right  px-4 mt-4 ml-3 bg-orange-600 hover:bg-orange-800 text-white font-bold py-2 px-6 rounded inline-flex items-center">
  <span class="mr-2">Sauvegarder l'article dans la base de donnée</span>
  <svg class="animate-spin h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
    <path fill-rule="evenodd" d="M10 0C4.477 0 0 4.477 0 10s4.477 10 10 10 10-4.477 10-10S15.523 0 10 0zm5.657 5.657l-1.414 1.414a7 7 0 1 0-1.414-1.414l1.414-1.414a9 9 0 1 1 1.414 1.414zM10 16a6 6 0 1 1 0-12 6 6 0 0 1 0 12z" clip-rule="evenodd" />
  </svg>
</button>

<div id="example" class="ml-3 mr-3"></div>

