<?php include_once("../App/Views/components/header.php")?>
<body>
<div class="py-16 bg-white">  
  <div class="container m-auto px-6 text-gray-600 md:px-12 xl:px-6">
      <div class="space-y-6 md:space-y-0 md:flex md:gap-6 lg:items-center lg:gap-12">
        <div class="md:5/12 lg:w-5/12">
          <img src="ressources/images/Web-Development02.svg" alt="image" loading="lazy" width="" height="">
        </div>
        <div class="md:7/12 lg:w-6/12">
          <h2 class="text-2xl text-gray-900 font-bold md:text-4xl">Le développement de Genius est réalisé par des développeurs passionnés</h2>
          <p class="mt-6 text-gray-600">Genius blog est un site internet qui dispose dans son catalogue d'une multitudfe d'articles orientées developpement web.</p>
          
          <p class="mt-6 text-gray-600">Le développement Web désigne de manière générale les tâches associées au développement de sites Web destinés à 
          être hébergés sur Internet. </p>
          <p class="mt-4 text-gray-600"> Nobis minus voluptatibus pariatur dignissimos libero quaerat iure expedita at? Asperiores nemo possimus nesciunt dicta veniam aspernatur quam mollitia.</p>
        </div>
      </div>
  </div>

</div>
<footer>
<?php include_once("../App/Views/components/footer.php")?>
</footer>
</body>

</html>