<?php include_once("../App/Views/components/header.php")?>
<body>
	

	<section class="bg-orange dark:bg-gray-900">
		<div
			class="bg-orange grid max-w-screen-xl px-4 py-8 mx-auto lg:gap-8 xl:gap-0 lg:py-16 lg:grid-cols-12 px-8 py-16">
			<div class="mr-auto place-self-center lg:col-span-7">
				<h1
					class="max-w-2xl mb-4 text-4xl font-extrabold leading-none md:text-6xl xl:text-6xl dark:text-white text-orange-800 text-justify">Un
					des meilleurs blogs dans le domaine du developpement web.</h1>
				<p
					class="max-w-2xl mb-6 font-light text-black-800 lg:mb-8 md:text-lg xl:text-2xl lg:text-xl dark:text-gray-400 text-justify">Que
					vous soyez developpeur web junior, senior ou expert avec des années
					d'expériences, vous decouvrirez forcément une nouvelle facette du
					codage sur le web a travers ce blog.</p>
				<a href="#"
					class="inline-flex items-center justify-center px-5 py-3 mr-3 text-base font-medium text-center text-white rounded-lg bg-orange-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 dark:focus:ring-blue-900">
					Commencer <svg class="w-5 h-5 ml-2 -mr-1" fill="currentColor"
						viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
						<path fill-rule="evenodd"
							d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z"
							clip-rule="evenodd"></path></svg>
				</a> <a href="#"
					class="inline-flex items-center justify-center px-5 py-3 text-base font-medium text-center text-gray-900 border border-gray-300 rounded-lg hover:bg-gray-100 focus:ring-4 focus:ring-gray-100 dark:text-white dark:border-gray-700 dark:hover:bg-gray-700 dark:focus:ring-gray-800">
					Rechercher un article </a>
			</div>
			<div class="hidden lg:mt-0 lg:col-span-5 lg:flex">
				<img src="ressources/images/hero.png" alt="mockup">
			</div>
		</div>
	</section>

	<div class="py-16 bg-gradient-to-br from-orange-50 to-orange-50">  
  <div class="container m-auto px-6 text-gray-600 md:px-12 xl:px-6">
      <div class="mb-12 space-y-2 text-center">
        <h2 class="text-2xl text-cyan-900 font-bold md:text-4xl">Consulter
					un article</h2>
        <p class="lg:w-6/12 lg:mx-auto">Vous
					souhaitez trouver la reponse a une question pour avancé dans votre
					métier de codeur web? Servez vous des mots-clés adaptés pour
					rechercher la solution dans notre catalogue d'articles.</p>
      </div>

      <div class="grid gap-12 lg:grid-cols-2">
        <div class="p-1 rounded-xl group sm:flex space-x-6 bg-white bg-opacity-50 shadow-xl hover:rounded-2xl">
          <img src="https://tailus.io/sources/blocks/twocards/preview/images/woman.jpg" alt="art cover" loading="lazy" width="1000" height="667" class="h-56 sm:h-full w-full sm:w-5/12 object-cover object-top rounded-lg transition duration-500 group-hover:rounded-xl">
          <div class="sm:w-7/12 pl-0 p-5">
            <div class="space-y-2">
              <div class="space-y-4">
                <h4 class="text-2xl font-semibold text-cyan-900">Quel est le meilleur langage de programmation ?</h4>
                <p class="text-gray-600">Laborum saepe laudantium in, voluptates ex placeat quo harum aliquam totam, doloribus eum impedit atque! Temporibus...</p>
              </div>
              <a href="www.tailus.io" class="block w-max text-cyan-600">Read more</a>
            </div>
          </div>
        </div>
        <div class="p-1 rounded-xl group sm:flex space-x-6 bg-white bg-opacity-50 shadow-xl hover:rounded-2xl">
          <img src="https://tailus.io/sources/blocks/twocards/preview/images/man.jpg" alt="art cover" loading="lazy" width="1000" height="667" class="h-56 sm:h-full w-full sm:w-5/12 object-cover object-top rounded-lg transition duration-500 group-hover:rounded-xl">
          <div class="sm:w-7/12 pl-0 p-5">
            <div class="space-y-2">
              <div class="space-y-4">
                <h4 class="text-2xl font-semibold text-cyan-900">Qui a créer JavaScript, le langage incontournable du developpement web ?</h4>
                <p class="text-gray-600">Laborum saepe laudantium in, voluptates ex placeat quo harum aliquam totam, doloribus eum impedit atque! Temporibus...</p>
              </div>
              <a href="www.tailus.io" class="block w-max text-cyan-600">Read more</a>
            </div>
          </div>
        </div>
      </div>
  </div>
</div>



	<section class="bg-gray-50 dark:bg-gray-800">
		<div class="py-8 px-4 mx-auto max-w-screen-xl sm:py-16 lg:px-6">
			<div class="max-w-screen-md mb-8 lg:mb-16">
				<h2
					class="mb-4 text-4xl font-extrabold text-gray-900 dark:text-white">Concu
					pour les passionnés du developpement web comme vous</h2>
				<p class="text-gray-500 sm:text-xl dark:text-gray-400">Genius
					Blog apporte des reponses concretes aux questions que la plupart
					des codeurs se posent et qui ont rapport avec la programmation
					informatique dans la catégorie du web.</p>
			</div>


			<section class="text-gray-600 body-font">
				<div class="container px-5 py-5 mx-auto">
					<div class="flex flex-wrap -m-4">
						<!--start here-->
						<?php include("../App/Views/components/article-home.php")?>
						<?php include("../App/Views/components/article-home.php")?>
						<?php include("../App/Views/components/article-home.php")?>
						<!--End here-->
					</div>
				</div>
			</section>
		</div>



	</section>






	<?php include_once("../App/Views/components/footer.php")?>
</body>
</html>