<?php include_once("../App/Views/components/header.php")?>
<body>
	<form method="post">
		<!-- Container -->
		<div class="container mx-auto py-14 ">
			<div class="flex justify-center px-6 my-12">
				<!-- Row -->
				<div class="w-full xl:w-3/4 lg:w-11/12 flex justify-center items-center sm:shadow-2xl">
					<!-- Col -->
					<div
						class="w-full h-auto pt-20 bg-white-400 hidden lg:block lg:w-5/12 bg-cover rounded-l-lg">
						<img src="ressources/images/hero-bg.svg" class="btn-" />

					</div>
					<!-- Col -->
					<div
						class="w-full lg:w-3/6 bg-white p-5 rounded-lg lg:rounded-l-none ">
						<h3 class="pb-8 pt-4 text-2xl text-center">Create an Account!</h3>
						<form class=" pt-6 pb-8 mb-4 bg-white rounded">
							<div class="mb-4">
							
									<label class="block mb-2 text-sm font-bold text-gray-700"
										for="lastName"> Pseudo </label> <input
										class="h-12 border-2 border-slate-500 w-full px-3 py-2 text-sm leading-tight text-gray-700 border rounded shadow appearance-none focus:outline-none focus:shadow-outline"
										id="lastName" name="Pseudo" type="text"
										placeholder="Pseudo" value="" />
							</div>
							<div class="mb-4">
								<label class="block mb-2 text-sm font-bold text-gray-700"
									for="email"> Email </label> <input
									class="h-12 border-2 border-slate-500 w-full px-3 py-2 mb-3 text-sm leading-tight text-gray-700 border rounded shadow appearance-none focus:outline-none focus:shadow-outline"
									id="email" type="email" name="Email" placeholder="Email"
									value="" />
							</div>
							<div class="mb-4">
								
									<label class="block mb-2 text-sm font-bold text-gray-700"
										for="password"> Password </label> <input
										class="h-12 border-2 border-slate-500 w-full px-3 py-2 mb-3 text-sm leading-tight text-gray-700 border  rounded shadow appearance-none focus:outline-none focus:shadow-outline"
										id="password" name="Password" type="password"
										placeholder="******************" />
									<label class="block mb-2 text-sm font-bold text-gray-700"
										for="c_password"> Confirm Password </label> <input
										class="h-12 border-2 border-slate-500 w-full px-3 py-2 mb-3 text-sm leading-tight text-gray-700 border rounded shadow appearance-none focus:outline-none focus:shadow-outline"
										id="c_password" name="ConfirmPassword" type="password"
										placeholder="******************" />
							</div>
							<div class="mb-6 text-center">
								<input
									class="h-12 w-full px-4 py-2 font-bold text-white bg-red-500 rounded-full hover:bg-blue-700 focus:outline-none focus:shadow-outline"
									type="submit" id="validation_inscription" value="Register Account" />
							</div>
							<hr class="mb-6 border-t" />
							
							<div class="text-center">
								<a
									class="inline-block text-sm text-blue-500 align-baseline hover:text-blue-800"
									href="?goto=<?= $this->datacrypt('home') ?>&action=<?= $this->datacrypt('view-login')
									?>">Already have an account? Login! 
								</a>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>

	</form>

  <?php include_once("../App/Views/components/footer.php")?>

  <script src="/ressources/js/inscription.js"></script>
</body>

</html>